backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "nyheter" # Used in routes, e.g., /admin/collections/blog
    label: "Nyheter" # Used in the UI
    folder: "content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: title
    fields: # The fields for each document, usually in front matter
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Bild", name: "img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "utbildning" # Used in routes, e.g., /admin/collections/blog
    label: "Utbildning" # Used in the UI
    folder: "content/utbildning" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Rubrik", name: "title", widget: "string"}
      - {label: "Publiceringsdatum", name: "date", widget: "datetime"}
      - {label: "Bild", name: "img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}